apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pdf-service-001-back
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pdf-service-001-back
    spec:
      containers:
      - name: pdf-service-001-back
        image: redis
        ports:
        - containerPort: 6379
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: pdf-service-001-back
spec:
  ports:
  - port: 6379
  selector:
    app: pdf-service-001-back
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pdf-service-001
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: pdf-service-001
    spec:
      containers:
      - name: pdf-service-001
        image: pdfservice001acr.azurecr.io/pdf-service-001:v1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: REDIS
          value: "pdf-service-001-back"
---
apiVersion: v1
kind: Service
metadata:
  name: pdf-service-001
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: pdf-service-001
